import { Transaction } from '@/pages/transactions/table/columns'

const dummyTransactions: Transaction[] = [
    {
        id: 1,
        date: new Date('2025-10-01'),
        amount: 100.0,
        name: 'Grocery shopping',
        description: 'Weekly grocery shopping at the local supermarket',
        category: 'Groceries',
    },
    {
        id: 2,
        date: new Date('2025-10-02'),
        amount: 50.0,
        name: 'Gas station',
        description: 'Fuel for the car',
        category: 'Transport',
    },
    {
        id: 3,
        date: new Date('2025-10-03'),
        amount: 200.0,
        name: 'Restaurant dinner',
        description: 'Dinner at a local restaurant with friends',
        category: 'Food',
    },
    {
        id: 4,
        date: new Date('2025-10-04'),
        amount: 300.0,
        name: 'PS5',
        description: 'Purchase of a new gaming console',
        category: 'Entertainment',
    },
    {
        id: 5,
        date: new Date('2025-10-05'),
        amount: 150.0,
        name: 'Medical checkup',
        description: 'Routine medical checkup at the clinic',
        category: 'Health',
    },
    {
        id: 6,
        date: new Date('2025-10-06'),
        amount: 80.0,
        name: 'Movie tickets',
        description: 'Tickets for a movie night with friends',
        category: 'Entertainment',
    },
    {
        id: 7,
        date: new Date('2025-10-07'),
        amount: 120.0,
        name: 'Monthly subscription',
        description: 'Subscription to a streaming service',
        category: 'Entertainment',
    },
    {
        id: 8,
        date: new Date('2025-10-08'),
        amount: 60.0,
        name: 'Public transport pass',
        description: 'Monthly pass for public transportation',
        category: 'Transport',
    },
    {
        id: 9,
        date: new Date('2025-10-09'),
        amount: 90.0,
        name: 'Pharmacy purchase',
        description: 'Medicines and health supplements',
        category: 'Health',
    },
    {
        id: 10,
        date: new Date('2025-10-10'),
        amount: 400.0,
        name: 'Monthly groceries',
        description: 'Groceries for the month including fresh produce and pantry staples',
        category: 'Food',
    },
    {
        id: 11,
        date: new Date('2025-10-11'),
        amount: 400.0,
        name: 'Monthly groceries',
        description: 'Groceries added for the month including fresh produce and pantry staples',
        category: 'Food',
    },
    {
        id: 12,
        date: new Date('2025-10-01'),
        amount: 100.0,
        name: 'Grocery shopping',
        description: 'Weekly grocery shopping at the local supermarket',
        category: 'Groceries',
    },
    {
        id: 13,
        date: new Date('2025-10-02'),
        amount: 50.0,
        name: 'Gas station',
        description: 'Fuel for the car',
        category: 'Transport',
    },
    {
        id: 14,
        date: new Date('2025-10-03'),
        amount: 200.0,
        name: 'Restaurant dinner',
        description: 'Dinner at a local restaurant with friends',
        category: 'Food',
    },
    {
        id: 15,
        date: new Date('2025-10-04'),
        amount: 300.0,
        name: 'PS5',
        description: 'Purchase of a new gaming console',
        category: 'Entertainment',
    },
    {
        id: 16,
        date: new Date('2025-10-05'),
        amount: 150.0,
        name: 'Medical checkup',
        description: 'Routine medical checkup at the clinic',
        category: 'Health',
    },
    {
        id: 17,
        date: new Date('2025-10-06'),
        amount: 80.0,
        name: 'Movie tickets',
        description: 'Tickets for a movie night with friends',
        category: 'Entertainment',
    },
    {
        id: 18,
        date: new Date('2025-10-07'),
        amount: 120.0,
        name: 'Monthly subscription',
        description: 'Subscription to a streaming service',
        category: 'Entertainment',
    },
    {
        id: 19,
        date: new Date('2025-10-08'),
        amount: 60.0,
        name: 'Public transport pass',
        description: 'Monthly pass for public transportation',
        category: 'Transport',
    },
    {
        id: 20,
        date: new Date('2025-10-09'),
        amount: 90.0,
        name: 'Pharmacy purchase',
        description: 'Medicines and health supplements',
        category: 'Health',
    },
    {
        id: 21,
        date: new Date('2025-10-10'),
        amount: 400.0,
        name: 'Monthly groceries',
        description: 'Groceries for the month including fresh produce and pantry staples',
        category: 'Food',
    },
    {
        id: 22,
        date: new Date('2025-10-11'),
        amount: 400.0,
        name: 'Monthly groceries',
        description: 'Groceries added for the month including fresh produce and pantry staples',
        category: 'Food',
    },
]

export default dummyTransactions;