const dummyTransactions = [
    {
        id: '1',
        date: '2025-10-01',
        amount: 100.0,
        description: 'Grocery shopping',
        category: 'Groceries',
    },
    {
        id: '2',
        date: '2025-10-02',
        amount: 50.0,
        description: 'Gas station',
        category: 'Transport',
    },
    {
        id: '3',
        date: '2025-10-03',
        amount: 200.0,
        description: 'Restaurant dinner',
        category: 'Food',
    },
    {
        id: '4',
        date: '2025-10-04',
        amount: 300.0,
        description: 'PS5',
        category: 'Entertainment',
    },
    {
        id: '5',
        date: '2025-10-05',
        amount: 150.0,
        description: 'Medical checkup',
        category: 'Health',
    },
    {
        id: '6',
        date: '2025-10-06',
        amount: 80.0,
        description: 'Movie tickets',
        category: 'Entertainment',
    },
    {
        id: '7',
        date: '2025-10-07',
        amount: 120.0,
        description: 'Monthly subscription',
        category: 'Entertainment',
    },
    {
        id: '8',
        date: '2025-10-08',
        amount: 60.0,
        description: 'Public transport pass',
        category: 'Transport',
    },
    {
        id: '9',
        date: '2025-10-09',
        amount: 90.0,
        description: 'Pharmacy purchase',
        category: 'Health',
    },
    {
        id: '10',
        date: '2025-10-10',
        amount: 400.0,
        description: 'Monthly groceries',
        category: 'Food',
    },
]